sudo: false
language: python

python:
  - "3.6"

before_script: export APP_SETTINGS="config.DevelopmentConfig"
install: pip install -U -r requirements/dev.txt
script:
  - flask routes
  - pip install travis-sphinx
  - cd docs/
  - travis-sphinx build -s . --nowarn

after_success:
  - travis-sphinx deploy